git clone https://github.com/mileszs/ack.vim.git $HOME/.vim/bundle/ack.vim/
git clone https://github.com/kien/ctrlp.vim.git $HOME/.vim/bundle/ctrlp.vim/
git clone https://github.com/Raimondi/delimitMate.git $HOME/.vim/bundle/dlimitmate/
git clone https://github.com/scrooloose/nerdtree.git $HOME/.vim/bundle/nerdtree/
git clone https://github.com/vim-scripts/Syntastic.git $HOME/.vim/bundle/syntastic/
git clone https://github.com/godlygeek/tabular.git $HOME/.vim/bundle/tabular/
git clone https://github.com/tomtom/tcomment_vim.git $HOME/.vim/bundle/tcomment_vim
git clone https://github.com/tpope/vim-fugitive.git $HOME/.vim/bundle/vim-fugitive/
git clone https://github.com/nathanaelkane/vim-indent-guides.git $HOME/.vim/bundle/vim-indent-guides/
git clone https://github.com/honza/vim-snippets.git $HOME/.vim/bundle/vim-snippets/
git clone https://github.com/tpope/vim-surround.git $HOME/.vim/bundle/vim-surround/
git clone https://github.com/VundleVim/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim/
