git clone https://github.com/mileszs/ack.vim.git ~/.vim/bundle/ack.vim/
git clone https://github.com/kien/ctrlp.vim.git ~/.vim/bundle/ctrlp.vim/
git clone https://github.com/Raimondi/delimitMate.git ~/.vim/bundle/dlimitmate/
git clone https://github.com/scrooloose/nerdtree.git ~/.vim/bundle/nerdtree/
git clone https://github.com/vim-scripts/Syntastic.git ~/.vim/bundle/syntastic/
git clone https://github.com/godlygeek/tabular.git ~/.vim/bundle/tabular/
git clone https://github.com/tomtom/tcomment_vim.git ~/.vim/bundle/tcomment_vim
git clone https://github.com/tpope/vim-fugitive.git ~/.vim/bundle/vim-fugitive/
git clone https://github.com/nathanaelkane/vim-indent-guides.git ~/.vim/bundle/vim-indent-guides/
git clone https://github.com/honza/vim-snippets.git ~/.vim/bundle/vim-snippets/
git clone https://github.com/tpope/vim-surround.git ~/.vim/bundle/vim-surround/
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim/
